<?php

/*
|--------------------------------------------------------------------------
| Forecourt Management Solutions - Business Data
|--------------------------------------------------------------------------
| Central data source for services, projects, FAQs and testimonials
| rendered across the site. Company contact details live in config/site.php.
*/

return [

    'services' => [
        [
            'slug' => 'tank-calibration',
            'title' => 'Tank Calibration',
            'heading' => 'Tank<br> Calibration',
            'icon' => 'fa-ruler-combined',
            'image' => 'images/redan.jpg',
            'excerpt' => 'Precision calibration for storage tanks and road tankers ensuring accurate fuel measurements and regulatory compliance.',
            'intro' => 'Accurate tank calibration is the foundation of fuel stock control. We calibrate underground storage tanks, above-ground tanks and road tankers to internationally recognised standards, producing certified calibration charts you can rely on.',
            'body' => [
                'Our technicians use precision dipping and volumetric techniques to generate accurate tank capacity tables for every compartment. Certified calibration charts protect your business against stock losses, reconciliation discrepancies and regulatory penalties.',
                'Whether you operate a single service station or a national fleet of road tankers, we deliver calibration services on-site with minimal disruption to your operations, and provide full documentation for legal metrology compliance in Zimbabwe.',
            ],
            'gallery' => ['images/dipping.jpg', 'images/tank.jpg', 'images/start.jpg', 'images/redann.jpg'],
        ],
        [
            'slug' => 'flowmeter-dispenser-calibration',
            'title' => 'Flowmeter & Dispenser Calibration',
            'heading' => 'Flowmeter &<br> Dispenser<br> Calibration',
            'icon' => 'fa-tachometer',
            'image' => 'images/meter.jpg',
            'excerpt' => 'Professional calibration of fuel dispensers and flowmeters to maintain accuracy and meet legal metrology standards.',
            'intro' => 'Every litre counts. We calibrate fuel dispensers and flowmeters so that what your customer pays for is exactly what they receive — keeping you compliant with trade measurement law and protecting your margins.',
            'body' => [
                'Using certified proving measures, our team verifies and adjusts dispenser and flowmeter accuracy across all product lines including petrol, diesel and paraffin. We test at multiple flow rates and document every result.',
                'Regular calibration prevents revenue leakage from over-dispensing, avoids penalties for under-dispensing, and builds customer trust in your brand. We offer scheduled calibration programmes for multi-site operators.',
            ],
            'gallery' => ['images/meter.jpg', 'images/pulser.jpg', 'images/vane.jpg', 'images/gear.jpg'],
        ],
        [
            'slug' => 'leak-pressure-testing',
            'title' => 'Leak & Pressure Testing',
            'heading' => 'Leak &<br> Pressure<br> Testing',
            'icon' => 'fa-search',
            'image' => 'images/reedan.jpg',
            'excerpt' => 'Advanced acoustic technology for comprehensive leak detection and pressure testing to ensure system integrity and safety.',
            'intro' => 'Undetected fuel leaks are an environmental hazard, a safety risk and a silent drain on profits. Our acoustic leak detection technology finds leaks in tanks and lines without excavation.',
            'body' => [
                'We perform precision pressure and vacuum testing on underground storage tanks, product lines and vapour recovery systems. Acoustic detection technology pinpoints leaks accurately, allowing targeted repairs instead of costly exploratory excavation.',
                'Routine leak and pressure testing keeps your site compliant with environmental regulations, protects groundwater, and gives you documented proof of system integrity for insurers and regulators.',
            ],
            'gallery' => ['images/pipe.jpg', 'images/joint.jpg', 'images/valve.jpg', 'images/vapor.jpg'],
        ],
        [
            'slug' => 'tank-cleaning-fuel-transshipment',
            'title' => 'Tank Cleaning & Fuel Transshipment',
            'heading' => 'Tank Cleaning<br> & Fuel<br> Transshipment',
            'icon' => 'fa-tint',
            'image' => 'images/clean.jpg',
            'excerpt' => 'Professional tank cleaning services and safe fuel transfer operations maintaining the highest safety and environmental standards.',
            'intro' => 'Contaminated tanks damage dispensers, block filters and put customer vehicles at risk. We clean storage tanks and safely transship fuel with certified equipment and trained crews.',
            'body' => [
                'Our tank cleaning service removes sludge, water and microbial contamination from underground and above-ground tanks. Fuel is safely pumped out, filtered where appropriate, and returned or transshipped to alternative storage.',
                'All work is carried out under strict safety procedures including gas-free certification, and waste is disposed of in an environmentally responsible manner.',
            ],
            'gallery' => ['images/clean.jpg', 'images/separoter.jpg', 'images/filter.jpg', 'images/hose.jpg'],
        ],
        [
            'slug' => 'fuel-pumps-dispensers',
            'title' => 'Fuel Pumps, Dispensers & Submersible Pumps',
            'heading' => 'Fuel Pumps,<br> Dispensers &<br> Submersibles',
            'icon' => 'fa-filter',
            'image' => 'images/submersive.jpg',
            'excerpt' => 'Supply, installation, and maintenance of fuel pumps, dispensers, and submersible pump systems for optimal performance.',
            'intro' => 'From single-nozzle pumps to multi-product electronic dispensers, we supply, install, repair and maintain the full range of forecourt dispensing equipment and submersible pumping systems.',
            'body' => [
                'We install and commission new dispensers, retrofit electronic heads and payment systems, and service mechanical components including meters, pulsers, vane pumps, solenoid valves, hoses, swivels and nozzles. Genuine spares are available through our online store.',
                'Our submersible pump services cover installation, replacement and performance testing, ensuring consistent flow rates across your forecourt even at peak demand.',
            ],
            'gallery' => ['images/bi-pump.jpg', 'images/submersive.jpg', 'images/opw.jpg', 'images/zva.jpg'],
        ],
        [
            'slug' => 'electrical-work',
            'title' => 'Commercial & Domestic Electrical Work',
            'heading' => 'Commercial &<br> Domestic<br> Electrical Work',
            'icon' => 'fa-bolt',
            'image' => 'images/elec.jpg',
            'excerpt' => 'Complete commercial and domestic electrical solutions including installation, maintenance, and emergency repairs.',
            'intro' => 'Forecourts are hazardous electrical environments that demand specialist knowledge. Our electricians handle everything from ATEX-rated forecourt installations to general commercial and domestic electrical work.',
            'body' => [
                'We design and install power distribution, lighting, canopy signage and control wiring for service stations, including explosion-proof (ATEX) fittings in hazardous zones. All installations are tested and certified.',
                'Beyond the forecourt, our team takes on commercial and domestic electrical installations, maintenance contracts and emergency repairs across Harare and beyond.',
            ],
            'gallery' => ['images/elec.jpg', 'images/solenoid.jpg', 'images/atex.jpg', 'images/ex50.jpg'],
        ],
    ],

    'projects' => [
        [
            'title' => 'Redan Service Station',
            'category' => 'construction',
            'tag' => 'Construction',
            'image' => 'images/harare.jpg',
            'description' => 'Full service station construction with modern fuel dispensers and underground tank installation.',
            'date' => 'March 2024',
            'location' => 'Harare',
        ],
        [
            'title' => 'Redan Chitungwiza',
            'category' => 'calibration',
            'tag' => 'Calibration',
            'image' => 'images/redan.jpg',
            'description' => 'Precision calibration of 50,000L underground storage tanks using acoustic measurement technology.',
            'date' => 'February 2024',
            'location' => 'Redan, Chitungwiza',
        ],
        [
            'title' => 'RK Services Station',
            'category' => 'installation',
            'tag' => 'Installation',
            'image' => 'images/kolo.jpg',
            'description' => 'Installation of 8 modern fuel dispensers with electronic payment systems and leak detection.',
            'date' => 'January 2024',
            'location' => 'Aspindale, Harare',
        ],
        [
            'title' => 'Mendip Energy Service Station',
            'category' => 'maintenance',
            'tag' => 'Maintenance',
            'image' => 'images/mendip.jpg',
            'description' => 'Complete maintenance and replacement of submersible pumps with performance testing.',
            'date' => 'December 2023',
            'location' => 'Mendip Energy',
        ],
        [
            'title' => 'Flowmeter Precision Calibration',
            'category' => 'calibration',
            'tag' => 'Calibration',
            'image' => 'images/redann.jpg',
            'description' => 'Calibration of electronic flowmeters for accurate fuel measurement and legal compliance.',
            'date' => 'November 2023',
            'location' => 'Redan Masasa, Harare',
        ],
        [
            'title' => 'Total Energies Service Station',
            'category' => 'construction',
            'tag' => 'Construction',
            'image' => 'images/start.jpg',
            'description' => 'Complete service station construction from the ground up, including tanks and forecourt equipment.',
            'date' => 'October 2023',
            'location' => 'Harare',
        ],
        [
            'title' => 'Underground Tank Installation',
            'category' => 'construction',
            'tag' => 'Construction',
            'image' => 'images/tank.jpg',
            'description' => 'Installation of double-wall underground tanks with environmental monitoring systems.',
            'date' => 'October 2023',
            'location' => 'Mutare',
        ],
        [
            'title' => 'Comprehensive Leak Testing',
            'category' => 'maintenance',
            'tag' => 'Maintenance',
            'image' => 'images/reedan.jpg',
            'description' => 'Advanced acoustic leak detection and pressure testing for underground storage systems.',
            'date' => 'September 2023',
            'location' => 'Redan, Chisipiti',
        ],
        [
            'title' => 'Service Station Electrical Work',
            'category' => 'installation',
            'tag' => 'Installation',
            'image' => 'images/elec.jpg',
            'description' => 'Complete electrical installation including lighting, power distribution, and safety systems.',
            'date' => 'August 2023',
            'location' => 'Harare',
        ],
    ],

    'stats' => [
        ['label' => 'Years of<br> Experience', 'value' => 10],
        ['label' => 'Projects<br> Completed', 'value' => 150],
        ['label' => 'Tanks<br> Calibrated', 'value' => 200],
        ['label' => 'Happy<br> Clients', 'value' => 100],
    ],

    'faqs' => [
        [
            'question' => 'What areas do you service?',
            'answer' => 'We are based in Graniteside, Harare and operate throughout Zimbabwe. Our teams regularly travel to service stations and fuel depots in Chitungwiza, Mutare, Bulawayo and everywhere in between.',
        ],
        [
            'question' => 'How often should fuel dispensers be calibrated?',
            'answer' => 'We recommend calibrating dispensers and flowmeters at least every six months, or immediately after any meter repair or component replacement. Regular calibration keeps you compliant with trade measurement regulations and prevents revenue loss.',
        ],
        [
            'question' => 'Can you detect a tank leak without digging up the forecourt?',
            'answer' => 'Yes. We use acoustic leak detection technology combined with pressure and vacuum testing to locate leaks in tanks and product lines without excavation. This pinpoints the problem so any repair work is targeted and minimal.',
        ],
        [
            'question' => 'Do you supply spare parts for pumps and dispensers?',
            'answer' => 'Yes. We stock and supply genuine spares including nozzles, hoses, swivels, breakaways, filters, meters, pulsers, solenoid valves and submersible pumps. Visit our online store or contact us for availability and pricing.',
        ],
        [
            'question' => 'Are your calibration certificates accepted by regulators?',
            'answer' => 'Our calibration work follows internationally recognised standards and we provide full documentation, including certified tank capacity tables and dispenser calibration reports suitable for legal metrology and audit purposes.',
        ],
        [
            'question' => 'How do I request a quote?',
            'answer' => 'Call us on +263 785 862 182, message us on WhatsApp, email us, or use the contact form on this website. Tell us your site location and the service you need, and we will respond with a quotation promptly.',
        ],
    ],

    'testimonials' => [
        [
            'text' => 'Forecourt Management Solutions calibrated all our underground tanks and dispensers with minimal disruption to trading. Their certificates passed our audit without a single query.',
            'name' => 'Service Station Manager',
            'role' => 'Redan, Chitungwiza',
        ],
        [
            'text' => 'Their acoustic leak testing found a line leak we had been chasing for months. Professional, fast and well priced — we now use them for all our maintenance.',
            'name' => 'Operations Director',
            'role' => 'Fuel Retailer, Harare',
        ],
        [
            'text' => 'From tank installation to dispenser commissioning, the team handled our new site build end to end. Excellent workmanship and genuinely knowledgeable engineers.',
            'name' => 'Site Developer',
            'role' => 'Service Station Owner, Mutare',
        ],
    ],

    'product_categories' => [
        'pumps' => 'Fuel Pumps',
        'nozzles' => 'Hoses & Nozzles',
        'meters' => 'Meters & Control',
        'accessories' => 'Fittings & Accessories',
        'lpg' => 'LPG Equipment',
        'safety' => 'Safety Equipment',
    ],

    'products' => [
        [
            'name' => 'PIUSI Bi-Pump',
            'category' => 'pumps',
            'tag' => 'Fuel Pumps',
            'image' => 'images/bi-pump.jpg',
            'description' => 'Versatile electric fuel transfer pump available in 12V or 24V DC configurations for mobile applications.',
            'features' => ['12V or 24V DC options', 'Suitable for diesel fuel', 'Portable design', 'Self-priming capability'],
        ],
        [
            'name' => 'PIUSI Panther 56/72',
            'category' => 'pumps',
            'tag' => 'Fuel Pumps',
            'image' => 'images/panther.jpg',
            'description' => 'AC powered fuel transfer pump for stationary installations with high flow rates.',
            'features' => ['AC powered operation', 'High flow rate capacity', 'Durable construction', 'Professional grade'],
        ],
        [
            'name' => 'PIUSI E120/E80 ATEX',
            'category' => 'pumps',
            'tag' => 'Fuel Pumps',
            'image' => 'images/atex.jpg',
            'description' => 'ATEX certified explosion-proof pumps for hazardous environments and professional applications.',
            'features' => ['ATEX certified', 'Explosion-proof design', 'E120 and E80 models', 'Safety compliance'],
        ],
        [
            'name' => 'PIUSI EX50/EX75 ATEX',
            'category' => 'pumps',
            'tag' => 'Fuel Pumps',
            'image' => 'images/ex50.jpg',
            'description' => 'Heavy-duty ATEX certified pumps for demanding industrial applications.',
            'features' => ['ATEX certified', 'EX50 and EX75 models', 'Industrial grade', 'Hazardous area approved'],
        ],
        [
            'name' => 'Submersible Pumps',
            'category' => 'pumps',
            'tag' => 'Fuel Pumps',
            'image' => 'images/submersive.jpg',
            'description' => 'Reliable submersible pumps for underground tank applications and fuel transfer operations.',
            'features' => ['Submersible design', 'Tank applications', 'Corrosion resistant', 'Various flow rates'],
        ],
        [
            'name' => 'Vane Pump',
            'category' => 'pumps',
            'tag' => 'Fuel Pumps',
            'image' => 'images/vane.jpg',
            'description' => 'Precision vane pumps for consistent fuel transfer with excellent metering accuracy.',
            'features' => ['Precision metering', 'Consistent flow', 'Durable vane design', 'Low maintenance'],
        ],
        [
            'name' => 'Gear Pump',
            'category' => 'pumps',
            'tag' => 'Fuel Pumps',
            'image' => 'images/gear.jpg',
            'description' => 'Heavy-duty gear pumps for high-pressure fuel transfer applications.',
            'features' => ['High pressure capability', 'Gear-driven design', 'Industrial applications', 'Reliable operation'],
        ],
        [
            'name' => 'Digital Fuel Dispenser',
            'category' => 'pumps',
            'tag' => 'Fuel Pumps',
            'image' => 'images/fuel.jpg',
            'description' => 'High-accuracy digital fuel dispensers for efficient and reliable forecourt fueling operations.',
            'features' => ['Digital flow meters', 'Durable weatherproof housing', 'Preset volume & price options', 'Multiple nozzle support'],
        ],
        [
            'name' => 'Fuel Dispensing Hose',
            'category' => 'nozzles',
            'tag' => 'Hoses & Nozzles',
            'image' => 'images/hose.jpg',
            'description' => 'Professional-grade petroleum transfer hose designed for fuel dispensing operations.',
            'features' => ['Chemical resistant', 'Various lengths available', 'Static dissipating wire', 'Fuel compatible'],
        ],
        [
            'name' => 'Auto Nozzles (OPW)',
            'category' => 'nozzles',
            'tag' => 'Hoses & Nozzles',
            'image' => 'images/opw.jpg',
            'description' => 'OPW automatic shut-off nozzles available in 2" and 1.5" configurations for fuel dispensing.',
            'features' => ['OPW brand quality', '2" and 1.5" sizes', 'Automatic shut-off', 'Spill prevention'],
        ],
        [
            'name' => 'Auto Nozzles (ZVA)',
            'category' => 'nozzles',
            'tag' => 'Hoses & Nozzles',
            'image' => 'images/zva.jpg',
            'description' => 'ZVA automatic nozzles with precision shut-off for professional fuel dispensing applications.',
            'features' => ['ZVA precision design', 'Automatic operation', 'Professional grade', 'Leak-proof sealing'],
        ],
        [
            'name' => 'Vapour Recovery Nozzle',
            'category' => 'nozzles',
            'tag' => 'Hoses & Nozzles',
            'image' => 'images/vapor.jpg',
            'description' => 'Environmental-friendly vapour recovery nozzles for emission control during fuel dispensing.',
            'features' => ['Vapour recovery system', 'Environmental compliance', 'Emission control', 'Safety features'],
        ],
        [
            'name' => 'Fuel Filters',
            'category' => 'accessories',
            'tag' => 'Filters',
            'image' => 'images/filter.jpg',
            'description' => 'Professional fuel filters for clean fuel transfer and engine protection in fuel systems.',
            'features' => ['High filtration efficiency', 'Engine protection', 'Various micron ratings', 'Durable construction'],
        ],
        [
            'name' => 'Fuel Truck Meter Register Valve',
            'category' => 'meters',
            'tag' => 'Meters & Registers',
            'image' => 'images/valve.jpg',
            'description' => 'Complete meter register valve assembly for fuel truck applications with accurate measurement.',
            'features' => ['Truck-mounted design', 'Accurate registration', 'Valve integration', 'Heavy-duty construction'],
        ],
        [
            'name' => 'Flowmeter',
            'category' => 'meters',
            'tag' => 'Meters',
            'image' => 'images/meter.jpg',
            'description' => 'Precision flowmeters for accurate fuel measurement and inventory control.',
            'features' => ['High accuracy', 'Digital display options', 'Multiple fluid types', 'Calibration certified'],
        ],
        [
            'name' => 'PIUSI Digital Flow Meters',
            'category' => 'meters',
            'tag' => 'Meters',
            'image' => 'images/meter.jpg',
            'description' => 'PIUSI K24 and other digital flow meters for precise fuel measurement and monitoring.',
            'features' => ['Digital display', 'High accuracy measurement', 'Easy installation', 'Multiple mounting options'],
        ],
        [
            'name' => 'Fill-Rite Mechanical Flow Meters',
            'category' => 'meters',
            'tag' => 'Meters',
            'image' => 'images/gear.jpg',
            'description' => 'Fill-Rite mechanical flow meters with analog displays for reliable fuel measurement.',
            'features' => ['Mechanical operation', 'No power required', 'Proven reliability', 'Easy maintenance'],
        ],
        [
            'name' => 'Mechanical Fuel Dispenser Computer',
            'category' => 'meters',
            'tag' => 'Meters',
            'image' => 'images/fuel.jpg',
            'description' => 'Internal mechanical computing unit for fuel dispensers with rotating number wheels for gallon and price calculation.',
            'features' => ['Mechanical operation', 'Gallon and price calculation', 'Rotating number display', 'Durable construction'],
        ],
        [
            'name' => 'Pulser',
            'category' => 'meters',
            'tag' => 'Control Systems',
            'image' => 'images/pulser.jpg',
            'description' => 'Electronic pulse transmitter for flow measurement integration with control systems.',
            'features' => ['Electronic pulse output', 'System integration', 'Accurate signal transmission', 'Reliable operation'],
        ],
        [
            'name' => 'Controller Assembly',
            'category' => 'meters',
            'tag' => 'Control Systems',
            'image' => 'images/pulser.jpg',
            'description' => 'Complete controller assembly for fuel system automation and monitoring.',
            'features' => ['System automation', 'Monitoring capabilities', 'Multiple input/output', 'User-friendly interface'],
        ],
        [
            'name' => 'Electronic Tank Level Gauges',
            'category' => 'meters',
            'tag' => 'Tank Monitoring',
            'image' => 'images/tank.jpg',
            'description' => 'Electronic tank level monitoring systems for underground fuel storage tanks with digital displays.',
            'features' => ['Real-time level monitoring', 'Digital display', 'Underground tank compatible', 'Accurate measurement'],
        ],
        [
            'name' => 'Kolor Kut Water Finding Paste',
            'category' => 'accessories',
            'tag' => 'Testing Equipment',
            'image' => 'images/kolo.jpg',
            'description' => 'Water detection paste for testing fuel tank contamination - changes color when it contacts water.',
            'features' => ['Water contamination detection', 'Color-changing indicator', 'Easy application', 'Reliable results'],
        ],
        [
            'name' => 'Fuel Sampling Equipment',
            'category' => 'accessories',
            'tag' => 'Testing Equipment',
            'image' => 'images/dipping.jpg',
            'description' => 'Stainless steel fuel sampling devices with graduated glass tubes for fuel quality testing and analysis.',
            'features' => ['Stainless steel construction', 'Graduated glass tubes', 'Multiple sizes available', 'Laboratory quality testing'],
        ],
        [
            'name' => 'Dipping Paste',
            'category' => 'accessories',
            'tag' => 'Tank Accessories',
            'image' => 'images/dipping.jpg',
            'description' => 'Reliable dipping paste for accurate detection of fuel or water levels in underground storage tanks.',
            'features' => ['High visibility color change', 'Quick and accurate readings', 'Compatible with fuel and water', 'Essential for manual tank gauging'],
        ],
        [
            'name' => 'Fuel System Pipes and Fittings',
            'category' => 'accessories',
            'tag' => 'Piping Systems',
            'image' => 'images/pipe.jpg',
            'description' => 'Specialized green fuel-rated pipes, elbows, couplings, and fittings for underground fuel piping systems.',
            'features' => ['Fuel-rated materials', 'Underground applications', 'Double-wall options', 'Complete fitting range'],
        ],
        [
            'name' => 'Solenoid Valve',
            'category' => 'accessories',
            'tag' => 'Valves',
            'image' => 'images/solenoid.jpg',
            'description' => 'Electronic solenoid valves for automated fuel system control and safety applications.',
            'features' => ['Electronic operation', 'Quick response', 'Various voltage options', 'Fail-safe design'],
        ],
        [
            'name' => 'Universal Joint',
            'category' => 'accessories',
            'tag' => 'Fittings',
            'image' => 'images/joint.jpg',
            'description' => 'High-quality universal joints for flexible connections in fuel handling systems.',
            'features' => ['Flexible connection', 'Stainless steel construction', 'Various sizes', 'Corrosion resistant'],
        ],
        [
            'name' => 'Swivel',
            'category' => 'accessories',
            'tag' => 'Fittings',
            'image' => 'images/swivel.jpg',
            'description' => 'Rotating swivel joints for hose connections allowing 360-degree rotation.',
            'features' => ['360-degree rotation', 'Leak-proof seals', 'Various thread sizes', 'Durable materials'],
        ],
        [
            'name' => 'LPG Separator',
            'category' => 'lpg',
            'tag' => 'LPG Equipment',
            'image' => 'images/separoter.jpg',
            'description' => 'High-quality LPG separator for gas-liquid separation in LPG systems.',
            'features' => ['Gas-liquid separation', 'Pressure rated', 'Safety certified', 'Durable construction'],
        ],
        [
            'name' => 'LPG Flowmeter',
            'category' => 'lpg',
            'tag' => 'LPG Equipment',
            'image' => 'images/separoter.jpg',
            'description' => 'Specialized flowmeter designed for accurate LPG measurement and dispensing applications.',
            'features' => ['LPG optimized', 'High accuracy', 'Pressure compensation', 'Temperature correction'],
        ],
        [
            'name' => 'LPG Safety & Differential Valve',
            'category' => 'lpg',
            'tag' => 'LPG Safety',
            'image' => 'images/valve.jpg',
            'description' => 'Essential safety and differential valve for LPG systems with pressure regulation.',
            'features' => ['Safety compliance', 'Pressure differential control', 'Emergency shut-off', 'Certified components'],
        ],
        [
            'name' => 'Breakaway',
            'category' => 'safety',
            'tag' => 'Safety Equipment',
            'image' => 'images/hose.jpg',
            'description' => 'Safety breakaway coupling for fuel hoses to prevent damage during accidental disconnection.',
            'features' => ['Safety protection', 'Automatic shut-off', 'Prevents spills', 'Easy reconnection'],
        ],
        [
            'name' => 'Shear Valve',
            'category' => 'safety',
            'tag' => 'Safety Equipment',
            'image' => 'images/solenoid.jpg',
            'description' => 'Impact-activated shear valve designed to automatically shut off fuel flow during dispenser collisions.',
            'features' => ['Automatic shut-off on impact', 'Prevents fuel spills', 'Fire safety compliance', 'Protects underground piping'],
        ],
    ],
];
